sylius_resource:
    resources:
        dotit_sylius_ease_of_payment_plugin.modality:
            driver: doctrine/orm
            classes:
                model: Dotit\SyliusEaseOfPaymentPlugin\Entity\Modality
                interface: Dotit\SyliusEaseOfPaymentPlugin\Entity\ModalityInterface
                factory: Sylius\Component\Resource\Factory\Factory
